### ISSUE TITLE
Upgrade breaks iOS push tokens

### ISSUE THREAD

**Issue by sluitz** [privacyidea/pi-authenticator#109]
It appears that (at least for me) the new app on iOS has multiple serious problems (iOS 14.4) - it's currently unusable:

1) After the upgrade, push tokens that worked in the old app are no longer displayed and don't work, no notification on the phone. 

2) Registering a new token completes successfully. It shows in the app (with @ replaced by %40). The PI server thinks it's registered and can then send a push to firebase (the server log says that the notification was submitted successfully). Nothing happens on the phone, however, no notification.

3) After terminating the app on the phone and starting it again, the newly registered token no longer shows. 

4) Synchronizing tokens (tapping 'sync') fails with a pop up that shows the non-existent token names (with @ replaced by %40), including the tokens from before the update. Deleting the app and reinstalling does not make a difference. The old tokens still show in the failure pop up after tapping 'sync'. They do not show in the regular token list. 

5) A new installation of the new app on a 14.4 phone where the authenticator was never installed before does not work either. Tokens can be registered, don't receive notifications and disappear from display when the app gets restarted.

6) Changing the new 'Enable polling' setting does not make any difference. 

Not sure how to debug this ... but I'd be happy to help if there is anything I can do. 

Best regards -- Steffen

**Comment by cornelinux** [comment]
Hello @sluitz 
thanks a lot for the detailed feedback. The will help to solve the problem.

Are you aware, that we have been offering beta versions in testflight for over two month?
We published that on the [community forum](https://community.privacyidea.org/t/privacyidea-authenticator-ios-testdrive/1753), on the [privacyIDEA Website](https://www.privacyidea.org/privacyidea-authenticator-ios-testdrive/) on a public newsletter and on our internal customers mailing list. Please consider subscribing to the [newsletter](https://netknights.it/en/newsletter/).

> After the upgrade, push tokens that worked in the old app are no longer displayed and don't work, no notification on the phone.

I assume that you still see the token in the token list but the push notification is not displayed anymore?
This could be due to an internal id change and tapping the sync would be the correct thing to do.

So when you tap "sync" please check the audit log in your privacyIDEA server for an entry with the "action" = "POST /ttype/<type>". You can also take a look at the privacyidea.log.

> A new installation of the new app on a 14.4 phone where the authenticator was never installed before does not work either. Tokens can be registered, don't receive notifications and disappear from display when the app gets restarted.

So it really vanishes from the list of the tokens in the main view?

Please try to enroll a token without a "@" in the token label. (The enrollment policies ``tokenlabel``  and ``tokenissuer``.)

**Comment by sluitz** [comment]
> Are you aware, that we have been offering beta versions in testflight for over two month?
> We published that on the [community forum](https://community.privacyidea.org/t/privacyidea-authenticator-ios-testdrive/1753), on the [privacyIDEA Website](https://www.privacyidea.org/privacyidea-authenticator-ios-testdrive/) on a public newsletter and on our internal customers mailing list. Please consider subscribing to the [newsletter](https://netknights.it/en/newsletter/).

I follow the community forum. 

> 
> > After the upgrade, push tokens that worked in the old app are no longer displayed and don't work, no notification on the phone.
> 
> I assume that you still see the token in the token list but the push notification is not displayed anymore?
> This could be due to an internal id change and tapping the sync would be the correct thing to do.

No, even the token is not displayed in the list anymore, it's not just the push notifications that are missing.
I see the same symptoms that are described in the community forum today: https://community.privacyidea.org/t/ios-app-v3-0-8-loses-push-tokens/1871. I also saw https://github.com/privacyidea/pi-authenticator/issues/110

> So when you tap "sync" please check the audit log in your privacyIDEA server for an entry with the "action" = "POST /ttype/". You can also take a look at the privacyidea.log.
>

> > A new installation of the new app on a 14.4 phone where the authenticator was never installed before does not work either. Tokens can be registered, don't receive notifications and disappear from display when the app gets restarted.
> 
> So it really vanishes from the list of the tokens in the main view?

Yes. Once the app is restarted the main view is empty. 

> 
> Please try to enroll a token without a "@" in the token label. (The enrollment policies `tokenlabel` and `tokenissuer`.)

I tried various variations of the token label. Spaces are displayed as %20. Not using any special characters doesn't make a difference. 

Best -- Steffen

**Comment by sluitz** [comment]
Update: I just received a push notification with a newly registered token - I don't know what changed, it just worked. That makes my problem identical to what is tracked in #110.

**Comment by nilsbehlen** [comment]
@sluitz ok will close this now. If you have any feedback regarding the apps in the beta channels please put them in #110.
