### ISSUE TITLE
PUSH token "accept" and "decline" buttons not showing on iOS

### ISSUE THREAD

**Issue by cbr46** [privacyidea/pi-authenticator#180]
When trying to authenticate using a PUSH token, we are encountering an issue. So far it only affects devices running iOS.

After opening the PrivacyIDEA Authenticator app with a press on the "Please confirm!"-notification, the token is not showing either the "accept" or "decline" buttons. It does not matter if the app is running in the background, currently closed or open at the time of the request. The buttons are not showing in any of these scenarios.

We already attempted to roll out new tokens but the problem persists.

PrivacyIDEA Authenticator version: 3.1.3
iOS version: 14.6

**Comment by timosturm** [comment]
Thank you for informing us about this issue. We are already aware of this and are working on it. The issue only affects iOS devices because of the different handling of push notifications on the platform. 

Rolling out new tokens will not fix this issue, a workaround is instead to enable polling in the app's settings. (This of course requires polling to be allowed by the server.)

**Comment by timosturm** [comment]
@cbr46 A fix for this bug will be available in version 3.1.4 of the app. If the issue persists on that version, please feel free to re-open this issue and leave a comment.
