### ISSUE TITLE
Write additional tests

### ISSUE THREAD

**Issue by timosturm** [privacyidea/pi-authenticator#44]
Test for this application should also include:

+ ~~parsing 2 step rollout uris~~
+ scanning qr codes
+ 2 step rollout
+ ~~combinations of tokens (algorithm x digits x type x secret x type of secret)~~

[Mocking](https://pub.dev/packages/mockito) could be useful here.

**Comment by frankmer** [comment]
scanning qr codes:
Scanning QR codes itself is not testable because we have no physical device and cannot mock the camera input, but parsing QR scanner result is tested.

2 step rollout:
Rolls out a HOTP and a TOTP token. Checks if the two-step window opens and if the length of the content matches the length of "step_output" of the rolledout token. Then, after the window is closed, the test looks for the token in the main view.
