### ISSUE TITLE
Show notification if screen is locked and app in foreground

### ISSUE THREAD

**Issue by nilsbehlen** [privacyidea/pi-authenticator#81]
Show notification if screen is locked and app is in foreground.

**Comment by nilsbehlen** [comment]
https://github.com/privacyidea/privacyidea-authenticator/issues/106

**Comment by timosturm** [comment]
This is already working in the current beta release (3.0.7).

**Comment by jmozd** [comment]
Just for the records:

(still running 3.0.7)

Throughout the last weeks, I repeatedly (but non-producibly) had the reported effect of not receiving notifications. Unlike my earlier report, it seems that having the app in the foreground is no necessary condition, this als happens when the app is active, but not in foreground. The only way to get notifications reliably is to close the app after each use.

Since I'm usually waiting for the app to ask, this is only a small nuisance, but I wanted to let you know.
Android version reported by phone is "8.0.0".
