### ISSUE TITLE
Receiving Push Notifications if the app isn't started

### ISSUE THREAD

**Issue by cbr46** [privacyidea/pi-authenticator#87]
Is it possible to implement a way that a user can receive push notifications without starting the app initially?

Currently the app must be started manually to get notifications from the Firebase server. Maybe there is a way to let the app run as background service like e.g. the Microsoft Authenticator?

Android version: 10
App version: 2.0.5

**Comment by plettich** [comment]
Hi,
the font/design issue is already WIP: #86 
I've transferred this issue to the repository for the new app to check for the push notification.

**Comment by timosturm** [comment]
@cbr46 

> However, if the app is opened and probably killed by the background manager no push notification is coming through. Even if I refresh pending push requests - no result. This problem does not affect everyone in our department, tho

What do you mean by probably?
Refreshing push notifications manually works completely independent of the normal push behavior. If manually refreshing does not get the challenge from the server, it might indicate a problem on the server site. This might be related to https://github.com/privacyidea/privacyidea/issues/2605.

A newer version of the app (3.0.12) has since been released on the app store, could you test that version and report back if the issue persists?

**Comment by cbr46** [comment]
@timosturm 
Hi,
sorry for the late reply. As far as we know this problem is solved.
